familyName: "Roboto"
buildStatic: false
buildSmallCap: false
sources:
  - "Roboto.designspace"
recipeProvider: "googlefonts"
recipe:
  # Unhinted variable family
  ../fonts/unhinted/Roboto[wdth,wght,ital].ttf:
    - source: "Roboto.designspace"
    - operation: exec
      exe: fontmake
      args: "-m Roboto.designspace -o variable --output-path ../fonts/unhinted/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: "gftools gen-stat"
      args: "../fonts/unhinted/Roboto[wdth,wght,ital].ttf --inplace"
    - postprocess: exec
      exe: ../scripts/instantiate_statics.py
      args: "../fonts/unhinted/Roboto[wdth,wght,ital].ttf ../fonts/unhinted/statics"
  # Hinted variable family
  ../fonts/hinted/Roboto[wdth,wght,ital].ttf:
    - source: "../fonts/unhinted/Roboto[wdth,wght,ital].ttf"
    - operation: buildVTT
      vttfile: "vtt-hinting.ttx" 
    - postprocess: exec
      exe: ../scripts/touchup_for_web.py
      args: "../fonts/hinted/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: ../scripts/instantiate_statics.py
      args: "../fonts/hinted/Roboto[wdth,wght,ital].ttf ../fonts/hinted/statics"
  # Android family
  ../fonts/android/Roboto[wdth,wght,ital].ttf:
    - source: "../fonts/unhinted/Roboto[wdth,wght,ital].ttf"
    # this shit still uses nototools
    - operation: exec
      exe: mkdir
      args: "-p ../fonts/android"
    - postprocess: exec
      exe: ../scripts/subset.py
      args: ../fonts/unhinted/Roboto[wdth,wght,ital].ttf ../fonts/android/Roboto[wdth,wght,ital].ttf
    - postprocess: exec
      exe: ../scripts/touchup_for_android.py
      args: "../fonts/android/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: ../scripts/instantiate_statics.py
      args: "../fonts/android/Roboto[wdth,wght,ital].ttf ../fonts/android/statics"
  # Web family
  ../fonts/web/Roboto[wdth,wght,ital].ttf:
    - source: "../fonts/hinted/Roboto[wdth,wght,ital].ttf"
    - operation: exec
      exe: mkdir
      args: "-p ../fonts/web/split"
    - postprocess: exec
      exe: ../scripts/subset_for_web.py
      args: "../fonts/hinted/Roboto[wdth,wght,ital].ttf ../fonts/web/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: ../scripts/touchup_for_web.py
      args: "../fonts/web/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: ../scripts/split_slnt_vf.py
      args: "../fonts/web/Roboto[wdth,wght,ital].ttf ../fonts/web/split"
    - postprocess: exec
      exe: ../scripts/instantiate_statics.py
      args: "../fonts/web/Roboto[wdth,wght,ital].ttf ../fonts/web/statics"
    - postprocess: exec
      exe: ../scripts/instantiate_condensed.py
      args: "../fonts/web/split/Roboto[wdth,wght].ttf ../fonts/web/split/Roboto-Italic[wdth,wght].ttf ../fonts/web/condensed"
  # ChromeOS
  ../fonts/chromeos/Roboto[wdth,wght,ital].ttf:
    - source: "../fonts/hinted/Roboto[wdth,wght,ital].ttf"
    - operation: exec
      exe: mkdir
      args: "-p ../fonts/chromeos"
    - postprocess: exec
      exe: ../scripts/subset_for_web.py
      args: "../fonts/hinted/Roboto[wdth,wght,ital].ttf ../fonts/chromeos/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: ../scripts/touchup_for_cros.py
      args: "../fonts/chromeos/Roboto[wdth,wght,ital].ttf"
    - postprocess: exec
      exe: ../scripts/instantiate_statics.py
      args: "../fonts/chromeos/Roboto[wdth,wght,ital].ttf ../fonts/chromeos/statics"